# Generated by Django 5.1.1 on 2024-09-19 15:16

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                max_length=14,
                unique=True,
                validators=[users.models.validate_phone_number],
            ),
        ),
    ]
